/*
 * lwan - web server
 * Copyright (c) 2026 L. A. F. Pereira <l@tia.mat.br>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 */

#define _GNU_SOURCE
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <math.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include "lwan-private.h"

#include "ringbuffer.h"
#include "lwan-array.h"
#include "lwan-strbuf.h"

#include "mod-lua-lsp.h" /* auto-generated by bin2hex */

#define FOR_EACH_LEXEME(X) X(VERBATIM) X(PRINT) X(LUA) X(ERROR) X(EOF)

#define GENERATE_ENUM(id) LEXEME_##id,

enum lexeme_type { FOR_EACH_LEXEME(GENERATE_ENUM) TOTAL_LEXEMES };

#undef GENERATE_ENUM

struct lexeme {
    enum lexeme_type type;
    struct lwan_value value;
};

DEFINE_RING_BUFFER_TYPE(lexeme_ring_buffer, struct lexeme, 4)

struct lexer {
    void *(*state)(struct lexer *);
    const char *start, *pos, *end;

    struct lexeme_ring_buffer ring_buffer;
};

/* FIXME: CivetWeb supports "Kepler Syntax", using <?lua ?> and
 * <% %> blocks (similar to <? ?>), in addition to <?lua= ?> and
 * <%= %> (corresponding to <?= ?>).  Support this in Lwan too. */
static const char left_meta[] = "<?";
static const char right_meta[] = "?>";
static_assert(sizeof(left_meta) == sizeof(right_meta),
              "right_meta and left_meta are the same length");

static void *lex_text(struct lexer *lexer);

static void error_vlexeme(struct lexeme *lexeme, const char *msg, va_list ap)
    __attribute__((format(printf, 2, 0)));
static void *lex_error(struct lexer *lexer, const char *msg, ...)
    __attribute__((format(printf, 2, 3)));

static void emit_lexeme(struct lexer *lexer, struct lexeme *lexeme)
{
    lexeme_ring_buffer_put(&lexer->ring_buffer, lexeme);
    lexer->start = lexer->pos;
}

static void emit(struct lexer *lexer, enum lexeme_type lexeme_type)
{
    struct lexeme lexeme = {
        .type = lexeme_type,
        .value = {.value = (char *)lexer->start,
                  .len = (size_t)(lexer->pos - lexer->start)}};
    emit_lexeme(lexer, &lexeme);
}

static int next(struct lexer *lexer)
{
    if (lexer->pos >= lexer->end)
        return EOF;
    int r = *lexer->pos;
    lexer->pos++;
    return r;
}

static size_t remaining(struct lexer *lexer)
{
    return (size_t)(lexer->end - lexer->pos);
}

static bool lex_streq(struct lexer *lexer, const char *str, size_t s)
{
    if (remaining(lexer) < s)
        return false;

    return !strncmp(lexer->pos, str, s);
}

static void ignore(struct lexer *lexer) { lexer->start = lexer->pos; }

static void backup(struct lexer *lexer) { lexer->pos--; }

static void error_vlexeme(struct lexeme *lexeme, const char *msg, va_list ap)
{
    char *formatted;
    size_t formatted_len;
    int r;

    *lexeme = (struct lexeme){.type = LEXEME_ERROR};

    r = vasprintf(&formatted, msg, ap);
    if (r < 0) {
        lexeme->value.value = strdup(strerror(errno));
        if (!lexeme->value.value)
            return;

        formatted_len = strlen(lexeme->value.value);
    } else {
        formatted_len = (size_t)r;
    }

    lwan_log_error("Error while parsing LSP: %.*s", (int)formatted_len,
                   formatted);
    free(formatted);
}

static void *lex_error(struct lexer *lexer, const char *msg, ...)
{
    struct lexeme lexeme;
    va_list ap;

    va_start(ap, msg);
    error_vlexeme(&lexeme, msg, ap);
    va_end(ap);

    emit_lexeme(lexer, &lexeme);
    return NULL;
}

static void *lex_lua(struct lexer *lexer)
{
    enum lexeme_type type = LEXEME_LUA;

    lexer->pos += strlen(left_meta);
    ignore(lexer);

    if (next(lexer) == '=') {
        type = LEXEME_PRINT;
        ignore(lexer);
    } else {
        backup(lexer);
    }

    do {
        if (lex_streq(lexer, right_meta, strlen(right_meta))) {
            emit(lexer, type);

            lexer->pos += strlen(right_meta);
            ignore(lexer);

            return lex_text;
        }
    } while (next(lexer) != EOF);

    return lex_error(lexer, "unexpected EOF");
}

static void *lex_text(struct lexer *lexer)
{
    do {
        if (lex_streq(lexer, left_meta, strlen(left_meta))) {
            if (lexer->pos > lexer->start)
                emit(lexer, LEXEME_VERBATIM);
            return lex_lua;
        }

        if (lex_streq(lexer, right_meta, strlen(right_meta))) {
            return lex_error(lexer, "unexpected script end tag");
        }
    } while (next(lexer) != EOF);

    if (lexer->pos > lexer->start)
        emit(lexer, LEXEME_VERBATIM);

    emit(lexer, LEXEME_EOF);
    return NULL;
}

static struct lexeme *lex_next(struct lexer *lexer)
{
    struct lexeme *lexeme;

    while (lexer->state) {
        lexeme = lexeme_ring_buffer_get_ptr_or_null(&lexer->ring_buffer);
        if (lexeme) {
            return lexeme;
        }

        lexer->state = lexer->state(lexer);
    }

    lexeme = lexeme_ring_buffer_get_ptr_or_null(&lexer->ring_buffer);
    if (lexeme) {
        return lexeme;
    }

    emit(lexer, LEXEME_EOF);
    return lexeme_ring_buffer_get_ptr_or_null(&lexer->ring_buffer);
}

static void lex_init(struct lexer *lexer, struct lwan_value input)
{
    lexer->state = lex_text;
    lexer->pos = lexer->start = input.value;
    lexer->end = input.value + input.len;
    lexeme_ring_buffer_init(&lexer->ring_buffer);
}

static char *compile_string(struct lwan_value file)
{
    struct lwan_strbuf output;
    struct lexer lexer;

    lex_init(&lexer, file);
    lwan_strbuf_init(&output);

    lwan_strbuf_append_value(&output, &lsp_header_value);

    while (true) {
        const struct lexeme *lexeme = lex_next(&lexer);
        switch (lexeme->type) {
        case LEXEME_VERBATIM:
            lwan_strbuf_append_strz(&output, "__request:write([======[");
            lwan_strbuf_append_value(&output, &lexeme->value);
            lwan_strbuf_append_strz(&output, "]======])\n");
            break;

        case LEXEME_LUA:
            lwan_strbuf_append_value(&output, &lexeme->value);
            lwan_strbuf_append_strz(&output, "\n");
            break;

        case LEXEME_PRINT:
            lwan_strbuf_append_strz(&output, "__request:write(");
            lwan_strbuf_append_value(&output, &lexeme->value);
            lwan_strbuf_append_strz(&output, ")\n");
            break;

        case LEXEME_EOF:
            lwan_strbuf_append_value(&output, &lsp_footer_value);
            return lwan_strbuf_get_buffer(&output);

        default:
            if (lexeme->value.len) {
                lwan_log_error("Error while compiling LSP: %.*s",
                               (int)lexeme->value.len, lexeme->value.value);
                free((char *)lexeme->value.value);
            }

            lwan_strbuf_free(&output);
            return NULL;
        }
    }
}

static bool has_valid_extension(const char *filename)
{
    const char *dot = strrchr(filename, '.');

    if (!dot) {
        return false;
    }

    return streq(dot, ".lua") || streq(dot, ".lsp") || streq(dot, ".lp");
}

char *lwan_mod_lua_lsp_to_lua(const char *filename)
{
    struct lwan_strbuf file;

    if (!has_valid_extension(filename)) {
        lwan_log_error("Path %s has invalid extension", filename);
        return NULL;
    }

    if (!lwan_strbuf_init_from_file(&file, filename)) {
        lwan_log_error("Could not load LSP from path: %s", filename);
        return NULL;
    }

    char *lua = compile_string(lwan_strbuf_to_value(&file));
    lwan_strbuf_free(&file);
    return lua;
}
