name: Build linux-debug-x86_64

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: apt update && apt install -y libdeflate-dev git cmake pkg-config libluajit-5.1-dev libsqlite3-dev libmariadb-dev build-essential ninja-build
        env:
          DEBIAN_FRONTEND: noninteractive
      - uses: actions/checkout@v6
      - name: Prepare build
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -B build -GNinja
      - name: Build
        run: ninja -C build
