name: Build freebsd-release-x86_64

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: freebsd
    steps:
      - uses: actions/checkout@v6
      - name: Prepare build
        run: cmake ${GITHUB_WORKSPACE} -DCMAKE_BUILD_TYPE=Release -B build -GNinja
      - name: Build
        run: ninja -C build
